# Generated by Django 3.2 on 2022-06-15 21:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20220615_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 15, 21, 39, 43, 621487, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
